#konfigurasi api gateway
server:
   port: 8765
spring:
   application:
      name: gateway-service
endpoints:
   reststart:
      enabled: true
   shutdown:
      enabled: true
   health:
      sensitive: false

#konfigurasi zuul proxy
zuul:
   prefix: /api
   routes:
      account:
         path: /account/**
         serviceId: account-service
      customer:
         path: /customer/**
         serviceId: customer-service
#konfigurasi ribbon
ribbon:
   eureka:
      enable: true
      
#konfigurasi eureka 
eureka:
   client:
      serviceUrl:
         defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
   instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
      
logging:
   level:
      ROOT: INFO
      org.springframework.web: DEBUG